### ISSUE TITLE
System.ObjectDisposedException on GetEvents call for multiple calendars

### ISSUE THREAD

**Issue by AllramEst83** [jfversluis/Plugin.Maui.CalendarStore#43]
Plugin.Maui.CalendarStore: v.1.0.1
VS 2022 - latest update. 

A System.ObjectDisposedException is thrown with the message "Cannot access a disposed object. Object name: 'Android.Database.CrossProcessCursorWrapper'." when calling GetEvents on Android. This occurs when fetching events for a single calendar. Below is the stack trace pointing towards the GetEvents method call in the CalendarStoreImplementation class.

```
   at Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:line 153
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualInt32Method(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 502
   at Android.Database.CursorWrapper.GetInt(Int32 columnIndex) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Database.CursorWrapper.cs:line 800
   at Plugin.Maui.CalendarStore.CalendarStoreImplementation.ToCalendar(ICursor cursor, List`1 projection)
   at Plugin.Maui.CalendarStore.CalendarStoreImplementation.GetCalendar(String calendarId)
   at Plugin.Maui.CalendarStore.CalendarStoreImplementation.GetEvents(String calendarId, Nullable`1 startDate, Nullable`1 endDate)
   at OurCalendar.MainPage.OnItemSelected(Object sender, SelectedItemChangedEventArgs e) in C:\dev\OurCalendar\OurCalendar\MainPage.xaml.cs:line 44
```

In my program file, I have the following line:
```
   builder.Services.AddSingleton<ICalendarStore>(CalendarStore.Default);
```

I have  tried both dependecy injecting it and using it statically.

If I put a try and catch around the GetEvents, I can get events for some calendars, and for others, it throws the exception even if there are events in that calendar.

I could show you a video of what's happening, but I don't know if I can add one to the issue.

Let me know if there is anything else I can provide you with.

**Comment by AllramEst83** [comment]
Just want to add that I have been looking at this for some days now. I built my own calendar service with the android `ContentResolver` to see what's going on when the calendars and events are queried. The weird thing is I can only fetch events for one calendar, and that one is a shared calendar from someone else. When I try to fetch my own Google calendar, I get nothing. It's like I don't have any events, but I do.

**Comment by AllramEst83** [comment]
Any ideas on what it can be?

**Comment by jfversluis** [comment]
I have not been able to look into it yet, sorry! Also a reproduction will help here to help me verify what we're looking at and that I am fixing the correct thing :)

**Comment by rojasjo** [comment]
@AllramEst83 I had the same issue that you are describing. I could fix it by making sure that I'm using the `CalendarStore` on the main thread. I hope that helps.

**Comment by AllramEst83** [comment]
Hi!

That's great to hear! I'll try it out in a new calendar app soon.

Working on another app at the moment 😊.

**Comment by AllramEst83** [comment]
Sweet! It worked. Now I will be building myself a calendar app.
